### ISSUE TITLE
error on starting the plugin

### ISSUE THREAD

**Issue by sandroklippel** [sandroklippel/cbers4a#3]
2021-06-29T15:50:58     WARNING    Traceback (most recent call last):
              File "/home/sandro/.local/share/QGIS/QGIS3/profiles/default/python/plugins/cbers4a/qgis_cbers4a_downloader.py", line 272, in update_collection
              year, month, day = int(mindate[0]), int(mindate[1]), int(mindate[2])
             ValueError: invalid literal for int() with base 10: '27T13:55:50'

* probably when updating collections

**Comment by joaopompeu** [comment]
Just had the same problem on Ubuntu 20: 021-09-12T23:25:36     WARNING    Traceback (most recent call last):
              File "/home/pompeu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/cbers4a/qgis_cbers4a_downloader.py", line 272, in update_collection
              year, month, day = int(mindate[0]), int(mindate[1]), int(mindate[2])
             ValueError: invalid literal for int() with base 10: '27T13:58:50'

Have anyone managed to solve this issue? 
I also cannot change the coordinate from the "search and download imagery", maybe due to this issue. 
Thanks

**Comment by sandroklippel** [comment]
This error prevents the plugin from updating the date availability field
but it still works.
Search coordinates are updated along with the canvas extent.

I will manage to fix the date issue soon.

Att,
Sandro.

Em dom., 12 de set. de 2021 às 23:29, joaopompeu ***@***.***>
escreveu:

**Comment by joaopompeu** [comment]
Thank you Sandro!
It works fine this way.

Best,
Joao

Em seg., 13 de set. de 2021 às 11:35, Sandro Klippel <
***@***.***> escreveu:
